import re
src = open('reference/opentui-0.5.11/packages/native/src/tests/utf8_test.zig').read()

def region(start_marker, end_marker):
    i = src.find(start_marker); assert i >= 0, start_marker
    j = src.find(end_marker, i); assert j >= 0, end_marker
    return src[i:j]

PAT = re.compile(
    r'\.name\s*=\s*"((?:[^"\\]|\\.)*)"\s*,\s*'
    r'\.input\s*=\s*("(?:[^"\\]|\\.)*"(?:\s*\*\*\s*\d+)?)\s*,\s*'
    r'\.expected\s*=\s*&\[_\]usize\{([^}]*)\}', re.S)

def triples(body):
    return [(m.group(1), m.group(2), m.group(3)) for m in PAT.finditer(body)]

REGIONS = [
    ('LINE_BREAK_GOLDEN', 'const line_break_golden_tests', 'test "line breaks: golden tests"'),
    ('TAB_STOP_GOLDEN', 'const tab_stop_golden_tests', 'test "tab stops: golden tests"'),
    ('LAYOUT_BREAK_GOLDEN', 'const layout_break_golden_tests', 'test "chunk layout scanner: golden break offsets"'),
]

def rust_input(lit):
    m = re.fullmatch(r'"((?:[^"\\]|\\.)*)"(?:\s*\*\*\s*(\d+))?', lit)
    assert m, lit
    s, rep = m.group(1), m.group(2)
    if rep:
        # expand comptime repeats to a literal (repeat bodies are escape-safe
        # to duplicate textually since escapes are per-character)
        return '"%s"' % (s * int(rep))
    return '"%s"' % s

def rust_exp(exp):
    parts = [p.strip() for p in exp.split(',') if p.strip()]
    return '&[%s]' % ', '.join(parts)

def emit():
    lines = []
    lines.append('// GENERATED by scripts/extract-utf8-goldens.py from')
    lines.append('// reference/opentui-0.5.11/packages/native/src/tests/utf8_test.zig')
    lines.append('// (line_break_golden_tests, tab_stop_golden_tests, layout_break_golden_tests).')
    lines.append('// DO NOT EDIT BY HAND; re-run the script with --emit.')
    for const, start, end in REGIONS:
        body = region(start, end)
        ts = triples(body)
        total = len(re.findall(r'\.name\s*=', body))
        assert total == len(ts), (const, total, len(ts))
        lines.append('const %s: &[(&str, &[usize])] = &[' % const)
        for name, lit, exp in ts:
            lines.append('    // %s' % name)
            lines.append('    (%s, %s),' % (rust_input(lit), rust_exp(exp)))
        lines.append('];')
        lines.append('')
    open('tests/golden_tables.inc', 'w').write('\n'.join(lines))
    print('wrote tests/golden_tables.inc')

if __name__ == '__main__':
    import sys
    if '--emit' in sys.argv:
        emit()
    else:
        allok = True
        for const, start, end in REGIONS:
            body = region(start, end)
            ts = triples(body)
            total = len(re.findall(r'\.name\s*=', body))
            ok = (total == len(ts))
            print(const, len(ts), '.name count:', total, 'OK' if ok else 'MISMATCH')
            allok &= ok
        print('ALL-OK' if allok else 'EXTRACTION-INCOMPLETE')
